# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Caio/Dropbox/Vfilter_2/project_1_filter/project_1_filter.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_2/design_1_ilmb_bram_if_cntlr_2.xci
# IP: The module: 'design_1_ilmb_bram_if_cntlr_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Caio/Dropbox/Vfilter_2/project_1_filter/project_1_filter.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_2/design_1_ilmb_bram_if_cntlr_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_bram_if_cntlr_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Caio/Dropbox/Vfilter_2/project_1_filter/project_1_filter.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_2/design_1_ilmb_bram_if_cntlr_2.xci
# IP: The module: 'design_1_ilmb_bram_if_cntlr_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Caio/Dropbox/Vfilter_2/project_1_filter/project_1_filter.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_2/design_1_ilmb_bram_if_cntlr_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_bram_if_cntlr_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
