set_property SRC_FILE_INFO {cfile:C:/Users/Caio/Dropbox/Vfilter_2/project_1_filter/project_1_filter.srcs/constrs_1/new/nexys4_constrs.xdc rfile:../../../project_1_filter.srcs/constrs_1/new/nexys4_constrs.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports Clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -add -name sysclk -period 10.00 -waveform {0 5} [get_ports Clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports reset]
