// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _otsu_HH_
#define _otsu_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "make_marker_faddfbkb.h"
#include "make_marker_fmul_cud.h"
#include "make_marker_fdiv_dEe.h"
#include "make_marker_sitofeOg.h"
#include "make_marker_fcmp_fYi.h"

namespace ap_rtl {

struct otsu : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<8> > histData_address0;
    sc_out< sc_logic > histData_ce0;
    sc_in< sc_lv<32> > histData_q0;
    sc_out< sc_lv<32> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<5> > ap_var_for_const1;


    // Module declarations
    otsu(sc_module_name name);
    SC_HAS_PROCESS(otsu);

    ~otsu();

    sc_trace_file* mVcdFile;

    make_marker_faddfbkb<1,5,32,32,32>* make_marker_faddfbkb_U1;
    make_marker_fmul_cud<1,4,32,32,32>* make_marker_fmul_cud_U2;
    make_marker_fdiv_dEe<1,16,32,32,32>* make_marker_fdiv_dEe_U3;
    make_marker_fdiv_dEe<1,16,32,32,32>* make_marker_fdiv_dEe_U4;
    make_marker_sitofeOg<1,6,32,32>* make_marker_sitofeOg_U5;
    make_marker_sitofeOg<1,6,32,32>* make_marker_sitofeOg_U6;
    make_marker_fcmp_fYi<1,1,32,32,1>* make_marker_fcmp_fYi_U7;
    sc_signal< sc_lv<65> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > reg_148;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<1> > tmp_5_reg_436;
    sc_signal< sc_lv<32> > grp_fu_135_p1;
    sc_signal< sc_lv<32> > reg_152;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_logic > ap_CS_fsm_state34;
    sc_signal< sc_lv<32> > grp_fu_118_p2;
    sc_signal< sc_lv<32> > reg_159;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_logic > ap_CS_fsm_state29;
    sc_signal< sc_logic > ap_CS_fsm_state55;
    sc_signal< sc_lv<32> > grp_fu_123_p2;
    sc_signal< sc_lv<32> > reg_167;
    sc_signal< sc_logic > ap_CS_fsm_state38;
    sc_signal< sc_logic > ap_CS_fsm_state59;
    sc_signal< sc_logic > ap_CS_fsm_state63;
    sc_signal< sc_lv<32> > t_cast2_fu_173_p1;
    sc_signal< sc_lv<32> > t_cast2_reg_386;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<9> > t_1_fu_183_p2;
    sc_signal< sc_lv<9> > t_1_reg_394;
    sc_signal< sc_lv<1> > exitcond_fu_177_p2;
    sc_signal< sc_lv<32> > tmp_1_fu_209_p2;
    sc_signal< sc_lv<32> > tmp_1_reg_425;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > threshold_3_cast1_fu_214_p1;
    sc_signal< sc_lv<32> > threshold_3_cast1_reg_430;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<9> > t_2_fu_226_p2;
    sc_signal< sc_lv<9> > t_2_reg_440;
    sc_signal< sc_lv<32> > wB_1_fu_237_p2;
    sc_signal< sc_lv<32> > wB_1_reg_450;
    sc_signal< sc_lv<1> > tmp_8_fu_243_p2;
    sc_signal< sc_lv<1> > tmp_8_reg_456;
    sc_signal< sc_lv<32> > wF_fu_249_p2;
    sc_signal< sc_lv<32> > wF_reg_460;
    sc_signal< sc_lv<32> > tmp_3_fu_261_p2;
    sc_signal< sc_lv<32> > tmp_3_reg_468;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_lv<32> > tmp_9_reg_478;
    sc_signal< sc_lv<32> > grp_fu_138_p1;
    sc_signal< sc_lv<32> > tmp_10_reg_483;
    sc_signal< sc_lv<32> > grp_fu_127_p2;
    sc_signal< sc_lv<32> > mB_reg_489;
    sc_signal< sc_logic > ap_CS_fsm_state50;
    sc_signal< sc_lv<32> > grp_fu_131_p2;
    sc_signal< sc_lv<32> > mF_reg_494;
    sc_signal< sc_lv<32> > varMax_1_fu_363_p3;
    sc_signal< sc_lv<32> > varMax_1_reg_499;
    sc_signal< sc_logic > ap_CS_fsm_state64;
    sc_signal< sc_lv<32> > threshold_1_fu_371_p3;
    sc_signal< sc_lv<32> > threshold_1_reg_504;
    sc_signal< sc_lv<9> > t_reg_72;
    sc_signal< sc_lv<32> > sum_reg_83;
    sc_signal< sc_lv<32> > wB_reg_95;
    sc_signal< sc_logic > ap_CS_fsm_state65;
    sc_signal< sc_lv<9> > threshold_2_reg_107;
    sc_signal< sc_lv<64> > tmp_fu_189_p1;
    sc_signal< sc_lv<64> > tmp_6_fu_232_p1;
    sc_signal< sc_lv<32> > threshold_fu_40;
    sc_signal< sc_lv<1> > tmp_s_fu_255_p2;
    sc_signal< sc_lv<32> > sumB_fu_44;
    sc_signal< sc_logic > ap_CS_fsm_state30;
    sc_signal< sc_lv<32> > varMax_fu_48;
    sc_signal< sc_lv<32> > grp_fu_118_p0;
    sc_signal< sc_lv<32> > grp_fu_118_p1;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state51;
    sc_signal< sc_lv<32> > grp_fu_123_p0;
    sc_signal< sc_lv<32> > grp_fu_123_p1;
    sc_signal< sc_logic > ap_CS_fsm_state35;
    sc_signal< sc_logic > ap_CS_fsm_state56;
    sc_signal< sc_logic > ap_CS_fsm_state60;
    sc_signal< sc_lv<32> > grp_fu_135_p0;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<9> > tmp_1_fu_209_p1;
    sc_signal< sc_lv<32> > wB_1_fu_237_p0;
    sc_signal< sc_lv<9> > tmp_3_fu_261_p1;
    sc_signal< sc_lv<32> > varBetween_to_int_fu_279_p1;
    sc_signal< sc_lv<32> > varMax_to_int_fu_297_p1;
    sc_signal< sc_lv<8> > tmp_14_fu_283_p4;
    sc_signal< sc_lv<23> > tmp_15_fu_293_p1;
    sc_signal< sc_lv<1> > notrhs_fu_321_p2;
    sc_signal< sc_lv<1> > notlhs_fu_315_p2;
    sc_signal< sc_lv<8> > tmp_16_fu_301_p4;
    sc_signal< sc_lv<23> > tmp_17_fu_311_p1;
    sc_signal< sc_lv<1> > notrhs4_fu_339_p2;
    sc_signal< sc_lv<1> > notlhs3_fu_333_p2;
    sc_signal< sc_lv<1> > tmp_18_fu_327_p2;
    sc_signal< sc_lv<1> > tmp_19_fu_345_p2;
    sc_signal< sc_lv<1> > tmp_20_fu_351_p2;
    sc_signal< sc_lv<1> > tmp_21_fu_141_p2;
    sc_signal< sc_lv<1> > tmp_22_fu_357_p2;
    sc_signal< sc_lv<2> > grp_fu_118_opcode;
    sc_signal< sc_lv<65> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<65> ap_ST_fsm_state1;
    static const sc_lv<65> ap_ST_fsm_state2;
    static const sc_lv<65> ap_ST_fsm_state3;
    static const sc_lv<65> ap_ST_fsm_state4;
    static const sc_lv<65> ap_ST_fsm_state5;
    static const sc_lv<65> ap_ST_fsm_state6;
    static const sc_lv<65> ap_ST_fsm_state7;
    static const sc_lv<65> ap_ST_fsm_state8;
    static const sc_lv<65> ap_ST_fsm_state9;
    static const sc_lv<65> ap_ST_fsm_state10;
    static const sc_lv<65> ap_ST_fsm_state11;
    static const sc_lv<65> ap_ST_fsm_state12;
    static const sc_lv<65> ap_ST_fsm_state13;
    static const sc_lv<65> ap_ST_fsm_state14;
    static const sc_lv<65> ap_ST_fsm_state15;
    static const sc_lv<65> ap_ST_fsm_state16;
    static const sc_lv<65> ap_ST_fsm_state17;
    static const sc_lv<65> ap_ST_fsm_state18;
    static const sc_lv<65> ap_ST_fsm_state19;
    static const sc_lv<65> ap_ST_fsm_state20;
    static const sc_lv<65> ap_ST_fsm_state21;
    static const sc_lv<65> ap_ST_fsm_state22;
    static const sc_lv<65> ap_ST_fsm_state23;
    static const sc_lv<65> ap_ST_fsm_state24;
    static const sc_lv<65> ap_ST_fsm_state25;
    static const sc_lv<65> ap_ST_fsm_state26;
    static const sc_lv<65> ap_ST_fsm_state27;
    static const sc_lv<65> ap_ST_fsm_state28;
    static const sc_lv<65> ap_ST_fsm_state29;
    static const sc_lv<65> ap_ST_fsm_state30;
    static const sc_lv<65> ap_ST_fsm_state31;
    static const sc_lv<65> ap_ST_fsm_state32;
    static const sc_lv<65> ap_ST_fsm_state33;
    static const sc_lv<65> ap_ST_fsm_state34;
    static const sc_lv<65> ap_ST_fsm_state35;
    static const sc_lv<65> ap_ST_fsm_state36;
    static const sc_lv<65> ap_ST_fsm_state37;
    static const sc_lv<65> ap_ST_fsm_state38;
    static const sc_lv<65> ap_ST_fsm_state39;
    static const sc_lv<65> ap_ST_fsm_state40;
    static const sc_lv<65> ap_ST_fsm_state41;
    static const sc_lv<65> ap_ST_fsm_state42;
    static const sc_lv<65> ap_ST_fsm_state43;
    static const sc_lv<65> ap_ST_fsm_state44;
    static const sc_lv<65> ap_ST_fsm_state45;
    static const sc_lv<65> ap_ST_fsm_state46;
    static const sc_lv<65> ap_ST_fsm_state47;
    static const sc_lv<65> ap_ST_fsm_state48;
    static const sc_lv<65> ap_ST_fsm_state49;
    static const sc_lv<65> ap_ST_fsm_state50;
    static const sc_lv<65> ap_ST_fsm_state51;
    static const sc_lv<65> ap_ST_fsm_state52;
    static const sc_lv<65> ap_ST_fsm_state53;
    static const sc_lv<65> ap_ST_fsm_state54;
    static const sc_lv<65> ap_ST_fsm_state55;
    static const sc_lv<65> ap_ST_fsm_state56;
    static const sc_lv<65> ap_ST_fsm_state57;
    static const sc_lv<65> ap_ST_fsm_state58;
    static const sc_lv<65> ap_ST_fsm_state59;
    static const sc_lv<65> ap_ST_fsm_state60;
    static const sc_lv<65> ap_ST_fsm_state61;
    static const sc_lv<65> ap_ST_fsm_state62;
    static const sc_lv<65> ap_ST_fsm_state63;
    static const sc_lv<65> ap_ST_fsm_state64;
    static const sc_lv<65> ap_ST_fsm_state65;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_21;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_36;
    static const sc_lv<32> ap_const_lv32_25;
    static const sc_lv<32> ap_const_lv32_3A;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_31;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_40;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_32;
    static const sc_lv<32> ap_const_lv32_22;
    static const sc_lv<32> ap_const_lv32_37;
    static const sc_lv<32> ap_const_lv32_3B;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<9> ap_const_lv9_100;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_FAAA;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state30();
    void thread_ap_CS_fsm_state34();
    void thread_ap_CS_fsm_state35();
    void thread_ap_CS_fsm_state38();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state50();
    void thread_ap_CS_fsm_state51();
    void thread_ap_CS_fsm_state55();
    void thread_ap_CS_fsm_state56();
    void thread_ap_CS_fsm_state59();
    void thread_ap_CS_fsm_state60();
    void thread_ap_CS_fsm_state63();
    void thread_ap_CS_fsm_state64();
    void thread_ap_CS_fsm_state65();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_exitcond_fu_177_p2();
    void thread_grp_fu_118_opcode();
    void thread_grp_fu_118_p0();
    void thread_grp_fu_118_p1();
    void thread_grp_fu_123_p0();
    void thread_grp_fu_123_p1();
    void thread_grp_fu_135_p0();
    void thread_histData_address0();
    void thread_histData_ce0();
    void thread_notlhs3_fu_333_p2();
    void thread_notlhs_fu_315_p2();
    void thread_notrhs4_fu_339_p2();
    void thread_notrhs_fu_321_p2();
    void thread_t_1_fu_183_p2();
    void thread_t_2_fu_226_p2();
    void thread_t_cast2_fu_173_p1();
    void thread_threshold_1_fu_371_p3();
    void thread_threshold_3_cast1_fu_214_p1();
    void thread_tmp_14_fu_283_p4();
    void thread_tmp_15_fu_293_p1();
    void thread_tmp_16_fu_301_p4();
    void thread_tmp_17_fu_311_p1();
    void thread_tmp_18_fu_327_p2();
    void thread_tmp_19_fu_345_p2();
    void thread_tmp_1_fu_209_p1();
    void thread_tmp_1_fu_209_p2();
    void thread_tmp_20_fu_351_p2();
    void thread_tmp_22_fu_357_p2();
    void thread_tmp_3_fu_261_p1();
    void thread_tmp_3_fu_261_p2();
    void thread_tmp_6_fu_232_p1();
    void thread_tmp_8_fu_243_p2();
    void thread_tmp_fu_189_p1();
    void thread_tmp_s_fu_255_p2();
    void thread_varBetween_to_int_fu_279_p1();
    void thread_varMax_1_fu_363_p3();
    void thread_varMax_to_int_fu_297_p1();
    void thread_wB_1_fu_237_p0();
    void thread_wB_1_fu_237_p2();
    void thread_wF_fu_249_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
