// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMAKE_MARKER_H
#define XMAKE_MARKER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmake_marker_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XMake_marker_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XMake_marker;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMake_marker_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMake_marker_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMake_marker_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMake_marker_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMake_marker_Initialize(XMake_marker *InstancePtr, u16 DeviceId);
XMake_marker_Config* XMake_marker_LookupConfig(u16 DeviceId);
int XMake_marker_CfgInitialize(XMake_marker *InstancePtr, XMake_marker_Config *ConfigPtr);
#else
int XMake_marker_Initialize(XMake_marker *InstancePtr, const char* InstanceName);
int XMake_marker_Release(XMake_marker *InstancePtr);
#endif

void XMake_marker_Start(XMake_marker *InstancePtr);
u32 XMake_marker_IsDone(XMake_marker *InstancePtr);
u32 XMake_marker_IsIdle(XMake_marker *InstancePtr);
u32 XMake_marker_IsReady(XMake_marker *InstancePtr);
void XMake_marker_EnableAutoRestart(XMake_marker *InstancePtr);
void XMake_marker_DisableAutoRestart(XMake_marker *InstancePtr);


void XMake_marker_InterruptGlobalEnable(XMake_marker *InstancePtr);
void XMake_marker_InterruptGlobalDisable(XMake_marker *InstancePtr);
void XMake_marker_InterruptEnable(XMake_marker *InstancePtr, u32 Mask);
void XMake_marker_InterruptDisable(XMake_marker *InstancePtr, u32 Mask);
void XMake_marker_InterruptClear(XMake_marker *InstancePtr, u32 Mask);
u32 XMake_marker_InterruptGetEnabled(XMake_marker *InstancePtr);
u32 XMake_marker_InterruptGetStatus(XMake_marker *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
